// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {exec} from '../models';

export function GetRequest(arg1:main.PostJSONData):Promise<string>;

export function PostRequest(arg1:main.PostJSONData):Promise<string>;

export function RenderTemplate(arg1:string,arg2:exec.Context):Promise<string>;
