// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {exec} from '../models';

export function Greet(arg1:string):Promise<string>;

export function RenderTemplate(arg1:string,arg2:exec.Context):Promise<string>;
